<?php
/** @var \Clerk\Clerk\Block\Powerstep $block */
?>
<div class="powerstep-success">
    <div class="powerstep-product">
        <img src="<?php echo $block->getImageUrl(); ?>">
            <?php echo __('You added %1 to your shopping cart.', $block->escapeHtml($block->getProduct()->getName())); ?>
    </div>
    <div class="powerstep-actions">
        <button class="action"
                data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getCartUrl(); ?>"}}'
                type="button" title="<?php echo __('Cart') ?>">
            <span><?php echo __('Cart') ?></span>
        </button>
        <button class="action primary"
                data-mage-init='{"redirectUrl":{"url":"<?php echo $block->getCheckoutUrl(); ?>"}}'
                type="button" title="<?php echo __('Proceed to Checkout'); ?>">
            <span><?php echo __('Proceed to Checkout'); ?></span>
        </button>
    </div>
</div>
<div class="powerstep-templates">
    <?php
    $Issetdataexclude = false;
    $dataexcludestring = '';
    $count = 0;
    foreach ($block->getTemplates() as $template) :
        $count++;
        $id = 'clerk_'.$block->generateRandomString();
        ?>
        <span class="clerk"
              id="<?php echo $id ?>"
              <?php if($Issetdataexclude) {
                  echo 'data-exclude-from="'.$dataexcludestring.'"';
              } ?>
              data-template="@<?php echo str_replace(' ','',$template); ?>"
              data-products="[<?php echo $block->getProduct()->getId(); ?>]"
              data-category="<?php echo $block->getProduct()->getCategoryId(); ?>"
        ></span>


        <?php

        if ($count == 1) {

            $dataexcludestring .= '#'.$id.':limit(4)';

        }else {

            $dataexcludestring .= ',#'.$id.':limit(4)';

        }
        $Issetdataexclude = true;
    endforeach; ?>
</div>