<?php
/** @var \Clerk\Clerk\Block\LiveSearch $block */
?>
<span
    class="clerk"
    data-template="@<?php echo $block->getLiveSearchTemplate(); ?>"
    data-instant-search-suggestions="<?php echo $block->getSuggestions(); ?>"
    data-instant-search-categories="<?php echo $block->getCategories(); ?>"
    data-instant-search-pages="<?php echo $block->getPages(); ?>"
    data-instant-search-pages-type="<?php echo $block->getPagesType(); ?>"
    data-instant-search="#search">
</span>
<style type="text/css">
#search_autocomplete { display: none !important; }
</style>