<?php
/** @var \Clerk\Clerk\Block\LiveSearch $block */
?>
<span
        class="clerk"
        data-template="@<?php echo $block->getLiveSearchTemplate(); ?>"
        data-instant-search-suggestions="<?php echo $block->getSuggestions(); ?>"
        data-instant-search-categories="<?php echo $block->getCategories(); ?>"
        data-instant-search-pages="<?php echo $block->getPages(); ?>"
        data-instant-search-pages-type="<?php echo $block->getPagesType(); ?>"
        data-instant-search-positioning="<?php echo $block->getDropdownPosition(); ?>"
<?php if (empty($block->getInputSelector())) {
    echo "data-instant-search=\"#search\">";
} else {
    echo "data-instant-search=\"".$block->getInputSelector()."\">";
}?>

</span>
<?php

if (!empty($block->getFormSelector())) {?>
    <script>
        require([
            'jquery',
            'jquery/ui',
            'domReady!'
        ], function($){
            $("<?php echo $block->getFormSelector(); ?>").each(function (){
                $(this).attr('action', '<?php echo $block->getUrl('catalogsearch/result');?>');
            });
        });
    </script>
<?php } ?>
<style type="text/css">
    #search_autocomplete { display: none !important; }
</style>
