<?php
/** @var \Clerk\Clerk\Block\PowerstepPopup $block */
$categoryIds = $block->getProduct() ? $block->getProduct()->getCategoryIds() : [];
?>
<?php if ($block->shouldShow()) : ?>
<div id="clerk_powerstep" class="clerk-popup">
    <div class="clerk_powerstep_header">
        <h2><?php echo $block->getHeaderText(); ?></h2>
    </div>
    <div class="clerk_powerstep_image">
        <img src="<?php echo $block->getImageUrl(); ?>" alt="<?php echo $block->getHeaderText(); ?>">
    </div>
    <div class="clerk_powerstep_clear actions">
        <button class="action primary clerk_powerstep_button clerk_powerstep_continue" onClick="location.href='<?php echo $block->getCartUrl(); ?>';"><?php echo __('Continue to Checkout'); ?></button>
        <button class="action clerk_powerstep_button clerk_powerstep_close"><?php echo __('Continue Shopping'); ?></button>
    </div>
    <div class="clerk_powerstep_templates">
    <?php
    $filter_duplicates = $block->getExcludeState();
    $slider_count = 0;
    $spanAttributes = [];
    $spanAttributes['class'] = 'clerk';
    $spanAttributes['products'] = $block->escapeHtmlAttr($block->getProduct()->getId());
    $spanAttributes['category'] = $block->escapeHtmlAttr(reset($categoryIds));

    foreach ($block->getTemplates() as $template):
        if($filter_duplicates){
            $spanAttributes['class'] = 'clerk clerk_' . (string)$slider_count;
        }
        if($slider_count > 0 && $filter_duplicates){
            $filter_string = '';
            for($i = 0; $i < $slider_count; $i++){
                if($i > 0){
                    $filter_string .= ', ';
                }
                $filter_string .= '.clerk_'.(string)$i;
            }
            $spanAttributes['exclude'] = $filter_string;
        }
    ?>
    <span
        class="<?php echo $spanAttributes['class']; ?>"
        <?php
        if($slider_count > 0 && $filter_duplicates){
            echo 'data-exclude-from="'.$spanAttributes['exclude'].'"';
        }
        ?>
        data-template="@<?php echo $block->escapeHtmlAttr($template); ?>"
        data-products="[<?php echo $spanAttributes['products']; ?>]"
        data-category="<?php echo $spanAttributes['category']; ?>"
    ></span>
    <?php
    $slider_count++;
    endforeach;
    ?>
    </div>
</div>
<script>
require(['jquery'], function($) {
    var popup = $("#clerk_powerstep");

    $(".clerk_powerstep_close").on("click", function() {
        popup.hide();
    });

    <?php if ($block->isAjax()) : ?>
    popup.show();
    <?php endif; ?>
});
</script>
<?php endif; ?>
